import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getStructuredPages } from "@/lib/notion";
import Link from "next/link";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/mode-toggle";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Impact Marine Group",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const rootPageId = process.env.NOTION_ROOT_PAGE_ID!;
  const structuredPages = await getStructuredPages(rootPageId);

  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex flex-col min-h-screen">
            <header className="border-b">
              <div className="container mx-auto px-4 py-4 flex justify-between items-center">
                <Link href="/" className="text-2xl font-bold">
                  Impact Marine Group
                </Link>
                <nav>
                  <ul className="flex space-x-4">
                    {structuredPages.map((page) => (
                      <li key={page.id}>
                        <Link href={`/${page.path}`} className="hover:underline">
                          {page.title}
                        </Link>
                      </li>
                    ))}
                  </ul>
                </nav>
                <ModeToggle />
              </div>
            </header>
            <main className="flex-grow container mx-auto px-4 py-8">
              {children}
            </main>
            <footer className="border-t">
              <div className="container mx-auto px-4 py-4 text-center">
                © 2024 Impact Marine Group. All rights reserved.
              </div>
            </footer>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
